In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [3]:
### all paths

nparray_dir = Path("../masks")
data_dir = Path("../data_financial")

### check if paths exist

exist = Path.exists(nparray_dir) and Path.exists(data_dir)
print(f"Exist: {exist}")

Exist: True

In [4]:
### define variables

experiment_date = "2008-05-07"

In [10]:
date_array: np.ndarray = np.load(nparray_dir / "only_date_nparray.npy", allow_pickle=True)
print(f"TYPE  : {type(date_array)}")
print(f"Shape : {date_array.shape}")
print(f"Values: {date_array}")

TYPE  : <class 'numpy.ndarray'>
Shape : (4392,)
Values: ['2008-05-07' '2008-05-08' '2008-05-09' ... '2026-04-15' '2026-04-16'
 '2026-04-17']

In [5]:
### TEST, on 2008-05-07 

df_dict = {
    "name":[],
    "path":[],
    "df":[],
    "shape":[]
}
for i, path in enumerate((data_dir / experiment_date).glob("*.csv")):
    try:
        tmp_df = pd.read_csv(path)
        shape = tmp_df.shape
    except Exception as e:
        shape = (0, 0)
    finally:
        print(str(i).rjust(2), "|", str(path.name).ljust(38), "|", shape)
        df_dict["name"].append(str(path.name))
        df_dict["path"].append(path)
        df_dict["df"].append(tmp_df)
        df_dict["shape"].append(shape)

 0 | derivatives_bars_daily_futures.csv     | (15, 29)
 1 | derivatives_bars_daily_options.csv     | (656, 37)
 2 | derivatives_bars_daily_options_225.csv | (296, 30)
 3 | equities_bars_daily.csv                | (2494, 42)
 4 | equities_earnings-calendar.csv         | (2, 7)
 5 | equities_investor-types.csv            | (3702, 56)
 6 | equities_master.csv                    | (2494, 13)
 7 | fins_details.csv                       | (0, 0)
 8 | fins_dividend.csv                      | (0, 0)
 9 | fins_summary.csv                       | (0, 0)
10 | indices_bars_daily.csv                 | (44, 6)
11 | indices_bars_daily_topix.csv           | (4392, 5)
12 | markets_breakdown.csv                  | (0, 0)
13 | markets_calendar.csv                   | (7305, 2)
14 | markets_margin-alert.csv               | (0, 0)
15 | markets_margin-interest.csv            | (0, 0)
16 | markets_short-ratio.csv                | (0, 0)

concat <strong>equities_bars_daily</strong> + <strong>equities_master</strong> by date column

In [6]:
equities_bars_daily: pd.DataFrame = df_dict["df"][3]
equities_master: pd.DataFrame = df_dict["df"][6]

In [7]:
### display both of dataframes

display(equities_bars_daily)
display(equities_master)

,Date,Code,O,H,L,C,UL,LL,Vo,Va,...,AC,AUL,ALL,AVo,AVa,AAdjO,AAdjH,AAdjL,AAdjC,AAdjVo
0,2008-05-07,13010,173.0,177.0,173.0,176.0,0,0,302000.0,5.291200e+07,...,176.0,0,0,131000.0,2.306100e+07,1770.0,1770.0,1750.0,1760.0,13100.0
1,2008-05-07,13050,1438.0,1441.0,1428.0,1436.0,0,0,73800.0,1.060824e+08,...,1436.0,0,0,16700.0,2.392430e+07,1435.0,1436.0,1428.0,1436.0,16700.0
2,2008-05-07,13060,1424.0,1432.0,1415.0,1425.0,0,0,5939800.0,8.459481e+09,...,1425.0,0,0,2686200.0,3.816480e+09,142.7,142.7,141.5,142.5,26862000.0
3,2008-05-07,13080,1422.0,1428.0,1413.0,1422.0,0,0,7227000.0,1.026724e+10,...,1422.0,0,0,4058000.0,5.748539e+09,1423.0,1423.0,1413.0,1422.0,4058000.0
4,2008-05-07,13100,903.0,911.0,900.0,905.0,0,0,3900.0,3.530200e+06,...,905.0,0,0,900.0,8.144000e+05,907.0,911.0,900.0,905.0,900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2489,2008-05-07,99900,403.0,413.0,403.0,406.0,0,0,10300.0,4.168600e+06,...,406.0,0,0,3800.0,1.538500e+06,270.7,271.3,268.7,270.7,5700.0
2490,2008-05-07,99910,445.0,445.0,441.0,442.0,0,0,8300.0,3.680100e+06,...,442.0,0,0,4600.0,2.036300e+06,443.0,443.0,441.0,442.0,4600.0
2491,2008-05-07,99930,1525.0,1525.0,1481.0,1481.0,0,0,3100.0,4.705000e+06,...,1481.0,0,0,2200.0,3.332600e+06,1525.0,1525.0,1481.0,1481.0,2200.0
2492,2008-05-07,99940,574.0,646.0,571.0,646.0,1,0,88200.0,5.395400e+07,...,646.0,1,0,55000.0,3.455060e+07,540.9,587.3,538.2,587.3,60500.0
2493,2008-05-07,99970,826.0,860.0,820.0,859.0,0,0,575550.0,4.821027e+08,...,859.0,0,0,331050.0,2.794023e+08,419.5,430.0,416.5,429.5,662100.0

,Date,Code,CoName,CoNameEn,S17,S17Nm,S33,S33Nm,ScaleCat,Mkt,MktNm,Mrgn,MrgnNm
0,2008-05-07,13010,極洋,"KYOKUYO CO.,LTD.",1,食品,50,水産・農林業,TOPIX Small 2,101,東証一部,2,貸借
1,2008-05-07,13050,大和証券投資信託委託株式会社 ダイワ上場投信−トピックス,Daiwa ETF-TOPIX,99,その他,9999,その他,-,109,その他,2,貸借
2,2008-05-07,13060,野村アセットマネジメント株式会社 ＴＯＰＩＸ連動型上場投資信託,TOPIX Exchange Traded Fund,99,その他,9999,その他,-,109,その他,2,貸借
3,2008-05-07,13080,日興アセットマネジメント株式会社 上場インデックスファンドＴＯＰＩＸ,Nikko Exchange Traded Index Fund TOPIX,99,その他,9999,その他,-,109,その他,2,貸借
4,2008-05-07,13100,大和証券投資信託委託株式会社 ダイワ上場投信−トピックス・コア３０,Daiwa ETF-TOPIX Core30,99,その他,9999,その他,-,109,その他,2,貸借
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2489,2008-05-07,99900,東京デリカ,"TOKYO DERICA CO.,LTD.",14,小売,6100,小売業,-,102,東証二部,1,信用
2490,2008-05-07,99910,ジェコス,GECOSS CORPORATION,13,商社・卸売,6050,卸売業,TOPIX Small 2,101,東証一部,2,貸借
2491,2008-05-07,99930,ヤマザワ,"YAMAZAWA CO.,LTD.",14,小売,6100,小売業,TOPIX Small 2,101,東証一部,1,信用
2492,2008-05-07,99940,やまや,YAMAYA CORPORATION,14,小売,6100,小売業,TOPIX Small 2,101,東証一部,2,貸借
2493,2008-05-07,99970,ベルーナ,"BELLUNA CO.,LTD.",14,小売,6100,小売業,TOPIX Small 2,101,東証一部,2,貸借

In [8]:
### check both Code columns are the same

code_3 = equities_bars_daily["Code"]
code_6 = equities_master["Code"]
if code_3.equals(code_6):
    print("Code columns are the same.")

Code columns are the same.

In [9]:
### concat both dataframes

concat_df = equities_master.merge(equities_bars_daily, on=["Date", "Code"], suffixes=("_1", "_2"))
print(f"Concatenated DataFrame shape: {concat_df.shape}")

Concatenated DataFrame shape: (2494, 53)

In [ ]:
concat_df[concat_df.isna().any(axis=1)].to_csv("tmp.csv", index=False)

In [12]:
concat_df.to_parquet("concat_df.parquet", index=False)

## concat はとりあえず完了！

ホモジニアスなグラフを作成するには，エッジを計算する必要がある．